// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chats.sql

package database

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (name, created_date)
VALUES ($1, CURRENT_TIMESTAMP)
RETURNING chat_id, created_date, name
`

func (q *Queries) CreateChat(ctx context.Context, name string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, name)
	var i Chat
	err := row.Scan(&i.ChatID, &i.CreatedDate, &i.Name)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats
WHERE chat_id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, chatID int32) error {
	_, err := q.db.ExecContext(ctx, deleteChat, chatID)
	return err
}
